import { Metadata } from 'next';
import { SimpleWidget, WidgetGrid } from '@/components';

export const metadata: Metadata = {
  title: 'Admin Dashboard',
  description: 'Generated by create next app',
};

export default function MainPage() {
  return (
    <div className='text-black p-2'>
      <h1 className='mt-2 text-3xl'>Dashboard</h1>
      <span className='text-xl'>General Info</span>

      <WidgetGrid />
    </div>
  );
}
